version: '3.8'
 
services:
  scoring-api:
    build:
      context: .
      platforms: 
        - linux/amd64
    # Mapeamos el puerto 8088 de tu host al puerto 8080 interno del contenedor
    ports:
      - "8088:8080" 
    restart: unless-stopped

